services:
  frontend:
    container_name: mern-blog_frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    container_name: mern-blog_backend
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  mongo:
    container_name: mern-blog_database
    image: mongo
    ports:
      - '27017:27017'
# to run : docker-compose up --build
