services:
  frontend:
    container_name: mern-blog_frontend
    build: ./frontend
    # network_mode: host
    ports:
      - '4000:3000'
    depends_on:
      - backend

  backend:
    container_name: mern-blog_backend
    build: ./backend
    # network_mode: host
    ports:
      - '5000:5000'
    depends_on:
      - database

  database: # service name
    container_name: mern-blog_database
    image: mongo
    # network_mode: host
    ports:
      - '7000:27017'
# to run : docker-compose up --build
